import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, Gauge, Thermometer, Waves, Zap } from 'lucide-react'
import { useLiveSensors } from '../hooks/useLiveSensors'

const colors = { temperature: '#ff956b', pressure: '#69b8ff', vibration: '#c18cff', humidity: '#4ed9bc', flow: '#f4bd58' }
const icons = { temperature: Thermometer, pressure: Gauge, vibration: Activity, humidity: Waves, flow: Zap }

function normalize(sensor, value) { const direction = sensor.direction === 'high' ? 1 : -1; return Math.max(0, Math.min(100, 50 + ((value - sensor.baseline) / sensor.baseline) * 100 * direction)) }
function SensorTooltip({ active, payload, label }) { if (!active || !payload?.length) return null; return <div className="live-sensor-tooltip"><strong>{new Date(label).toLocaleTimeString([], { minute: '2-digit', second: '2-digit' })}</strong>{payload.map((item) => <span key={item.dataKey}><i style={{ background: item.color }} />{item.name}: {Number(item.value).toFixed(1)}%</span>)}</div> }
export default function LiveSensorPanel() { const { sensors } = useLiveSensors(); const primary = sensors[0]; const chartData = primary.history.map((point, index) => { const row = { time: point.timestamp.getTime() }; sensors.forEach((sensor) => { row[sensor.id] = normalize(sensor, sensor.history[index]?.value ?? sensor.value) }); return row }); return <section className="live-sensor-panel"><div className="live-sensor-heading"><div><span className="pm-live"><i />REAL-TIME SENSOR MATRIX</span><h2>Live equipment signals</h2><p>AI is correlating five sensor streams against each asset's healthy baseline.</p></div><div className="sensor-stream-status"><strong>{sensors.length}</strong><span>streams online<small>updating every 1.5s</small></span></div></div><div className="sensor-signal-grid">{sensors.map((sensor) => { const Icon = icons[sensor.id]; return <div className="sensor-signal" key={sensor.id}><span className="sensor-signal-icon" style={{ '--signal-color': colors[sensor.id] }}><Icon size={15} /></span><div><small>{sensor.type}</small><strong>{sensor.formattedValue} <em>{sensor.unit}</em></strong><span className={`sensor-state sensor-state-${sensor.status.toLowerCase()}`}><i />{sensor.status} · {sensor.percentageChange >= 0 ? '+' : ''}{sensor.percentageChange.toFixed(1)}%</span></div></div> })}</div><div className="live-sensor-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 10, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="#263e59" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="time" type="number" domain={['dataMin', 'dataMax']} tickFormatter={(value) => new Date(value).toLocaleTimeString([], { minute: '2-digit', second: '2-digit' })} axisLine={false} tickLine={false} tick={{ fill: '#718aa5', fontSize: 10 }} minTickGap={42} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} axisLine={false} tickLine={false} tick={{ fill: '#718aa5', fontSize: 10 }} width={38} /><Tooltip content={<SensorTooltip />} />{sensors.map((sensor) => <Line key={sensor.id} type="monotone" dataKey={sensor.id} name={sensor.type} stroke={colors[sensor.id]} strokeWidth={2.2} dot={false} isAnimationActive={false} />)}</LineChart></ResponsiveContainer></div><div className="sensor-chart-legend">{sensors.map((sensor) => <span key={sensor.id}><i style={{ background: colors[sensor.id] }} />{sensor.type}</span>)}<b>100% = high deviation from baseline</b></div></section> }
